from .assignment import TestAssignment
from .boolean_statements import TestBooleanStatements
from .control_structures import TestControlStructures
from .functions import TestFunctions
from .math import TestMath
from .names import TestNames
from .references import TestReferences
from .syntax_errors import TestSyntaxErrors
from .templates import TestTemplates
